In [1]:
import pandas as pd

In [7]:
import os
os.listdir("../data")

['Australian_Beer_Production_218_Observations.xlsx']

In [24]:
df = pd.read_excel("../data/Australian_Beer_Production_218_Observations.xlsx")
df.head()

   Observation  Year Quarter   Period  Beer Production (ML)
0            1  1956      Q1  1956 Q1                   284
1            2  1956      Q2  1956 Q2                   213
2            3  1956      Q3  1956 Q3                   227
3            4  1956      Q4  1956 Q4                   308
4            5  1957      Q1  1957 Q1                   262

In [25]:
df['Date'] = df['Year'].astype(str) + df['Quarter'].astype(str)
df['Date'] = pd.PeriodIndex(df["Date"], freq="Q").to_timestamp()
df = df.set_index("Date")

In [26]:
df.head()

            Observation  Year Quarter   Period  Beer Production (ML)
Date
1956-01-01            1  1956      Q1  1956 Q1                   284
1956-04-01            2  1956      Q2  1956 Q2                   213
1956-07-01            3  1956      Q3  1956 Q3                   227
1956-10-01            4  1956      Q4  1956 Q4                   308
1957-01-01            5  1957      Q1  1957 Q1                   262

In [23]:
df.index.to_timestamp()

DatetimeIndex(['1956-01-01', '1956-04-01', '1956-07-01', '1956-10-01',
               '1957-01-01', '1957-04-01', '1957-07-01', '1957-10-01',
               '1958-01-01', '1958-04-01',
               ...
               '2008-01-01', '2008-04-01', '2008-07-01', '2008-10-01',
               '2009-01-01', '2009-04-01', '2009-07-01', '2009-10-01',
               '2010-01-01', '2010-04-01'],
              dtype='datetime64[us]', name='Date', length=218, freq='QS-OCT')